name: Bot CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'bot/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t registry.launchpencil.f5.si/zikanwari:bot && docker push registry.launchpencil.f5.si/zikanwari:bot
      working-directory: ./bot
